Improve error handling in bootstrap script

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -e # Exit on any error
+set -euo pipefail # Exit on error, unset var usage, or failed pipeline
 
 if [ "$EUID" -eq 0 ]; then
   echo "Don't run this script as root."
